#pragma once

#include "CoreMinimal.h"
#include "GameplayTagContainer.h"
#include "NativeGameplayTags.h"

struct FTLVGameplayTags
{
	static const FTLVGameplayTags& Get() { return GameplayTags;}
	static void InitializeNativeGameplayTags();

	FGameplayTag Attributes_Primary_Health;

	FGameplayTag InputTag_LMB;
	FGameplayTag InputTag_RMB;
	FGameplayTag InputTag_1;
	FGameplayTag InputTag_2;
	FGameplayTag InputTag_3;
	FGameplayTag InputTag_4;
	FGameplayTag Shoot;
	FGameplayTag Reload;
	FGameplayTag Damage;
	FGameplayTag Effects_HitReact;
private:
	static FTLVGameplayTags GameplayTags;
};

namespace TLVGameplayTags
{
	TLV_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move)
	TLV_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_EquipAxe)
	TLV_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UnequipAxe)
	TLV_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LightAttack_Axe)
	TLV_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_HeavyAttack_Axe)

	TLV_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Axe)
	TLV_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Unequip_Axe)
	TLV_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Melee_Light_Axe)
	TLV_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Melee_Heavye_Axe)
	TLV_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Hit_Pause)

	TLV_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip_Axe)	
	TLV_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Unequip_Axe)	
	TLV_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Hit_Pause)

	TLV_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Axe)	
	TLV_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_JumpToFinisher)
	
	TLV_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_AttackType_Light)
	TLV_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_AttackType_Heavy)

	TLV_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Melee)

	TLV_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_Melee_Hit)
	TLV_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_HitReact_Light_Front_Head)
	TLV_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_HitReact_Light_Front_Torso)
	TLV_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_HitReact_Light_Left_Head_Down)
	TLV_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_HitReact_Light_Left_Head_Up)
	TLV_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_HitReact_Light_Left_Torso)
	TLV_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_HitReact_Light_Right_Head_Up)
	TLV_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_HitReact_Light_Right_Head_Down)
	TLV_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_HitReact_Light_Right_Torso)

	TLV_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_HitReact_Heavy_Front_Head)
	TLV_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_HitReact_Heavy_Front_Torso)
	TLV_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_HitReact_Heavy_Left_Head_Down)
	TLV_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_HitReact_Heavy_Left_Head_Up)
	TLV_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_HitReact_Heavy_Left_Torso)
	TLV_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_HitReact_Heavy_Right_Head_Up)
	TLV_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_HitReact_Heavy_Right_Head_Down)
	TLV_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_HitReact_Heavy_Right_Torso)

	TLV_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_SetByCaller_BaseDamage)
	
	TLV_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Melee)

	TLV_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_HitReact)
	TLV_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_Death)

	TLV_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_Death)
	
	TLV_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Status_Strafing)


}